name: ${project.name}
main: ${mainclass}
version: ${project.version}
description: ${project.description}
author: ${author}
softdepend: [mcMMO,MobArena,Vault]
commands:
   StatsGui:
      description: Hide or show the mcMMO stats gui.
      usage: /StatsGui [Hide|Show]